site_name: OmniPython-template
theme:
  name: material
  palette:
    scheme: slate
nav:
  - Home: index.md
  - Architecture: architecture.md
markdown_extensions:
  - admonition
  - pymdownx.superfences
